### ISSUE TITLE
Final enhancements for copy/translation

### ISSUE THREAD

**Issue by glueckpress** [deworg/get-involved-flyer#3]
Final correction and enhancements of all copy for v1.0.

**Comment by Zodiac1978** [comment]
Bei Community kann das "(...)" raus, das ist ein Überbleibsel von einer unfertigen Übersetzung.
At the topic "community" you can remove the "(...)" - this is just a leftover from an unfinished translation.

**Comment by Zodiac1978** [comment]
From Skype:
Translate all the things -> Übersetze einfach alles

**Comment by Zodiac1978** [comment]
From Skype:
Just "Dokumentation" (instead of Docs/Dokumentation)

**Comment by Zodiac1978** [comment]
From Skype:
Video-Box: Trennung müsste "ten" abtrennen und nicht nur das "en" (bei "eingereichten")
http://www.duden.de/sprachwissen/rechtschreibregeln/worttrennung

**Comment by glueckpress** [comment]
[Mehrsprachler](https://github.com/deworg/get-involved-flyer/commit/4c63cb989141cc905475508dd14a05b2db3a9446#diff-a2a6c4bd515d4de621c369407b962a0dR38) ist laut Duden tatsächlich _kein_ Wort, habe ich mich geirrt.  Hab’s zurückgesetzt auf _Übersetzung_, das passt auch im Kontext der Überschriften wirklich besser.

**Comment by glueckpress** [comment]
Wenn bis Montagabend niemand mehr schreit, schließe das issue und leg’ los, @StephanieWiermann! :wink:

**Comment by florianbrinkmann** [comment]
> Bringe Menschen zusammen durch Events wie Meetups und WordCamps und mache Öffentlichkeitsarbeit.

Das ist der einzige Satz mit einem Punkt, daher vielleicht den Punkt weglassen (oder bei den anderen einen hin)?
Und ich meine, dass „Bringe Menschen durch Events wie Meetups und WordCamps zusammen und mache Öffentlichkeitsarbeit.“ sich etwas runder anhört?

> Prüfe eingereichte Themes, um die Qualität des Theme- Verzeichnisses zu erhalten

Da ist ein Leerzeichen zwischen „Theme-“ und „Verzeichnisses“ :)

**Comment by glueckpress** [comment]
Issue hiermit geschlossen. @StephanieWiermann, der Text gehört dir! :)
